// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import frc.robot.commands.*;
import frc.robot.subsystems.*;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import frc.robot.subsystems.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 * This class is where the bulk of the robot should be declared.  Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls).  Instead, the structure of the robot
 * (including subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
// The robot's subsystems
    public final Climber m_climber = new Climber();
    public final ele m_ele = new ele();
    public final intake m_intake = new intake();
    public final DriveTrain m_driveTrain = new DriveTrain();
    public final HDrive m_hDrive = new HDrive();

// Joysticks
private final XboxController operator = new XboxController(1);
private final Joystick joystick1 = new Joystick(0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  
  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /**
  * The container for the robot.  Contains subsystems, OI devices, and commands.
  */
  private RobotContainer() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Smartdashboard Subsystems
    SmartDashboard.putData(m_intake);
    SmartDashboard.putData(m_driveTrain);


    // SmartDashboard Buttons
    SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
    SmartDashboard.putData("DriveDistance", new DriveDistance( m_driveTrain ));
    SmartDashboard.putData("intakeRun: my_In", new intakeRun(1, m_intake));
    SmartDashboard.putData("intakeRun: my_Out", new intakeRun(-1, m_intake));
    SmartDashboard.putData("ele run: up", new elerun(1, m_ele));
    SmartDashboard.putData("ele run: down", new elerun(-1, m_ele));
    SmartDashboard.putData("HDrive Run: Left", new HDriveRun(1));
    SmartDashboard.putData("HDrive Run: Right", new HDriveRun(-1));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Configure the button bindings
    configureButtonBindings();

    // Configure default commands
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND
    m_driveTrain.setDefaultCommand(new DriveWithJoySticks(0, 0, m_driveTrain) );


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND
    m_driveTrain.setDefaultCommand(new DriveWithJoySticks(() -> joystick1.getRawAxis(0), () -> joystick1.getRawAxis(1) , m_driveTrain) );

    // Configure autonomous sendable chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings.  Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
// Create some buttons
final JoystickButton eledownbutton = new JoystickButton(operator, XboxController.Button.kY.value);        
eledownbutton.whenHeld(new elerun(-1, m_ele) ,true);
    SmartDashboard.putData("ele down button",new elerun(-1, m_ele) );

final JoystickButton eleupbutton = new JoystickButton(operator, XboxController.Button.kX.value);        
eleupbutton.whenHeld(new elerun(1, m_ele) ,true);
    SmartDashboard.putData("ele up button",new elerun(1, m_ele) );

final JoystickButton intakeoutbutton = new JoystickButton(operator, XboxController.Button.kB.value);        
intakeoutbutton.whenHeld(new intakeRun(-1, m_intake) ,true);
    SmartDashboard.putData("intake out button",new intakeRun(-1, m_intake) );

final JoystickButton intatkerunbutton = new JoystickButton(operator, XboxController.Button.kA.value);        
intatkerunbutton.whenHeld(new intakeRun(1, m_intake) ,true);
    SmartDashboard.putData("intatke run button",new intakeRun(1, m_intake) );

final JoystickButton climberDown = new JoystickButton(joystick1, 1);        
climberDown.whenHeld(new ClimbRun(0) ,true);
    SmartDashboard.putData("Climber Down",new ClimbRun(0) );

final JoystickButton climberup = new JoystickButton(joystick1, 2);        
climberup.whenHeld(new ClimbRun(0) ,true);
    SmartDashboard.putData("Climber up",new ClimbRun(0) );

final JoystickButton hDriveRight = new JoystickButton(joystick1, 3);        
hDriveRight.whenHeld(new HDriveRun(0) ,true);
    SmartDashboard.putData("HDrive Right",new HDriveRun(0) );

final JoystickButton hDriveLeft = new JoystickButton(joystick1, 4);        
hDriveLeft.whenHeld(new HDriveRun(0) ,true);
    SmartDashboard.putData("HDrive Left",new HDriveRun(0) );



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
public Joystick getJoystick1() {
        return joystick1;
    }

public XboxController getOperator() {
      return operator;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
  */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
  

}

